### ISSUE TITLE
LnpOrder Class does not have getNotes() method

### ISSUE THREAD

**Issue by MattDN93** [Bandwidth/java-bandwidth-iris#10]
The LnpOrder class does not have the same getNotes() method as the Order class. This is a problem because you cannot query notes on an LNPOrder since calling getNotes() for an Order that is not of type LNPOrder does not work.

Since the API endpoint supports calling /notes on the /orders/ and the /portIns/ resource, I fixed this by adding the same methods from the Order class to the LnpOrder class and changing the orderId and URI path before recompiling the SDK:

```
    public void addNote(Note note) throws Exception {
        client.put(client.buildAccountModelUri(new String[] { IrisPath.LNP_URI_PATH, orderId, "notes" }), note);
    }

    public Notes getNotes() throws Exception {
        return client.get(client.buildAccountModelUri(new String[] { IrisPath.LNP_URI_PATH, orderId, "notes" }), Notes.class);
    }
```

I'll add a PR and unit tests soon.

**Comment by jmulford-bandwidth** [comment]
Hi @MattDN93,

Thanks for pointing this and https://github.com/Bandwidth/java-bandwidth-iris/issues/11 out! Are you still working on a PR for this? We can review it once it's done.

Thank you,

Jacob

**Comment by dtolbert-bw** [comment]
Hey @MattDN93 let us know if you're planning on opening a pull request, we'll review and merge ASAP. 

Until then, we're gonna close the issue.

Thanks!
-DT
