### ISSUE TITLE
No OrderHistory model for any objects

### ISSUE THREAD

**Issue by MattDN93** [Bandwidth/java-bandwidth-iris#11]
` /accounts /{accountId} /orders /{orderid} /history `
` /accounts /{accountId} /portins /{orderid} /history `

These APIs return the history of an order.

Neither of these resources have corresponding models in the Java SDK. I fixed this by adding an `Order.java` and `OrderHistoryWrapper.java` in /model as well as creating corresponding `getHistory()` methods to the `LnpOrder` and `Order` classes. Will PR and add the files soon.

**Comment by dtolbert-bw** [comment]
Hey @MattDN93 let us know if you're planning on opening a pull request, we'll review and merge ASAP. 

Until then, we're gonna close the issue.

Thanks!
-DT
