### ISSUE TITLE
Typo in Visibility

### ISSUE THREAD

**Issue by ajrice6713** [Bandwidth/java-bandwidth-iris#33]
https://github.com/Bandwidth/java-bandwidth-iris/blob/37dbb138b44d6825a4527c3a346addd656f994ae/src/main/java/com/bandwidth/iris/sdk/model/LidbTnGroup.java#L20

There is a typo in this string that causes invalid XML to be generated on a required field and any order will fail 

Should be `Visibility` not `Visibilty`

**Comment by cbraam** [comment]
Please remove me.

**Comment by hamermike** [comment]
Hi @cbraam, you can Unwatch the repository via GitHub but as this is a public repo we're unable to change your settings.
