### ISSUE TITLE
Fix lata field name in TelephoneNumber

### ISSUE THREAD

**Issue by v-ladynev** [Bandwidth/java-bandwidth-iris#34]
Get order endpoint returns a phone number lata in the element `LATA` (not `Lata`)
```java
@XmlRootElement(name = "TelephoneNumber")
@XmlAccessorType(XmlAccessType.FIELD)
public class TelephoneNumber {

    @XmlElement(name = "FullNumber")
    protected String fullNumber;

    @XmlElement(name = "City")
    protected String city;

    @XmlElement(name = "Lata")
    protected String lata;

}
```

https://github.com/Bandwidth/java-bandwidth-iris/blob/master/src/main/java/com/bandwidth/iris/sdk/model/TelephoneNumber.java#L19

**Comment by hamermike** [comment]
Hi @v-ladynev - Thank you for taking the time to report this! We'll take a look and get this updated.
