### ISSUE TITLE
LnpOrder.get does not return orderId

### ISSUE THREAD

**Issue by stratzoomer** [Bandwidth/java-bandwidth-iris#8]
The response from the REST call to ``` GET /accounts /{accountId} /portins/{order_id} ``` does not return the order_id field in the XML, like the com.bandwidth.iris.sdk.model.LnpOrder.get() method expects. This makes the orderId field in the LnpOrder object null, which was causing us issues during LOA upload.
This can be easily fixed on the SDK side by explicitly setting the orderId. I am submitting a PR for this. https://github.com/Bandwidth/java-bandwidth-iris/pull/9

**Comment by dtolb** [comment]
https://github.com/Bandwidth/java-bandwidth-iris/pull/9
